# Generated by Django 4.1.7 on 2023-03-02 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='activation_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
